name: accidents-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - matplotlib
  - seaborn
  - requests
  - geopandas        
  - pyproj           
  - scikit-learn     
  - jupyterlab>=3.0.0
  - ipykernel
  - ipywidgets
  - tqdm
  - plotly